name: app_store_connect_api
description: A wrapper for the App Store Connect API. Meant for the `automatic_version_upgrader`.
homepage: https://github.com/tomassasovsky/app_store_connect_api.dart
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto_keys: ^0.3.0
  dart_jsonwebtoken: ^2.4.2
  equatable: ^2.0.3
  http: ^0.13.5
  jose: ^0.3.2
  meta: ^1.8.0
  pub_semver: ^2.1.1
  universal_io: ^2.0.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

false_secrets:
  - /test/src/models/app_store_credentials_test.dart
  - /test/src/app_store_connect_api_test.dart
